

<?php $__env->startSection('content'); ?>

<!DOCTYPE html>
<html>

<head>
    <title>Data Table Example</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.17.0/xlsx.full.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.dataTables.css">
    <link href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/all.min.css" rel="stylesheet">

    <style>
        .slide-bottom {
            -webkit-animation: slide-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
            animation: slide-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
        }

        /* ----------------------------------------------
 * Generated by Animista on 2024-6-18 12:6:41
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

        /**
 * ----------------------------------------
 * animation slide-bottom
 * ----------------------------------------
 */
        @-webkit-keyframes slide-bottom {
            0% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
            }

            100% {
                -webkit-transform: translateY(100px);
                transform: translateY(100px);
            }
        }

        @keyframes  slide-bottom {
            0% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
            }

            100% {
                -webkit-transform: translateY(100px);
                transform: translateY(100px);
            }
        }



        .scale-in-bottom {
            -webkit-animation: scale-in-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
            animation: scale-in-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
        }

        /* ----------------------------------------------
 * Generated by Animista on 2024-5-28 16:29:42
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

        /**
 * ----------------------------------------
 * animation scale-in-bottom
 * ----------------------------------------
 */
        @-webkit-keyframes scale-in-bottom {
            0% {
                -webkit-transform: scale(0);
                transform: scale(0);
                -webkit-transform-origin: 50% 100%;
                transform-origin: 50% 100%;
                opacity: 1;
            }

            100% {
                -webkit-transform: scale(1);
                transform: scale(1);
                -webkit-transform-origin: 50% 100%;
                transform-origin: 50% 100%;
                opacity: 1;
            }
        }

        @keyframes  scale-in-bottom {
            0% {
                -webkit-transform: scale(0);
                transform: scale(0);
                -webkit-transform-origin: 50% 100%;
                transform-origin: 50% 100%;
                opacity: 1;
            }

            100% {
                -webkit-transform: scale(1);
                transform: scale(1);
                -webkit-transform-origin: 50% 100%;
                transform-origin: 50% 100%;
                opacity: 1;
            }



        }
    </style>
</head>

<body style="padding-top: 4rem;">



    <div class="max-w-6xl mx-auto mt-5 bg-white shadow-md rounded-lg overflow-hidden">
        <div class="px-6 py-4">
            <h1 class="text-xl font-semibold">Student Attendance</h1>
        </div>
        <?php if(session('success')): ?>
        <div id="successMessage" class="alert alert-success">
            <?php echo e(session('success')); ?>

        </div>
        <?php endif; ?>
        <div class="flex flex-wrap shadow-sm px-6 py-4">
            <a href="<?php echo e(route('student.create')); ?>" class="px-4 py-2 mb-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-s-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-blue-500 dark:focus:text-white">
                Register
            </a>
            <a href="#" onclick="openModal()" class="px-4 py-2 mb-2 text-sm font-medium text-gray-900 bg-white border-t border-b border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-blue-500 dark:focus:text-white">
                Import
            </a>
            <a href="<?php echo e(url('/generate-qrcodes')); ?>" aria-current="page" class="px-4 py-2 mb-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 hover:bg-gray-100 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-blue-500 dark:focus:text-white">
                Generate QRCodes
            </a>
            <a href="<?php echo e(route('students.all-qrcodes')); ?>" class="px-4 py-2 mb-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-blue-500 dark:focus:text-white">
                View all QRCodes
            </a>
            <a href="<?php echo e(route('exportToExcel')); ?>" class="px-4 py-2 mb-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-blue-500 dark:focus:text-white">
                Grades with attendance
            </a>
            <a href="<?php echo e(route('attendance.manual')); ?>" class="px-4 py-2 mb-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-blue-500 dark:focus:text-white">
                Mark Grades Manually
            </a>
            <form action="<?php echo e(route('export')); ?>" method="GET" class="mb-2">
                <button type="submit" class="px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-blue-500 dark:focus:text-white">
                    Student Grades
                </button>
            </form>
            <form action="<?php echo e(url('/send-email')); ?>" method="GET">
                <button type="submit" class="px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-e-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-blue-500 dark:focus:text-white">
                    Email Results
                </button>
            </form>
        </div>





        <div class="px-6 py-4">
            <!-- Search Bar -->
            <div class="flex justify-between items-center mb-4">
                <form action="<?php echo e(route('attendance')); ?>" method="GET" class="flex w-1/2">
                    <input type="text" name="search" class="w-3/4 p-2 border border-gray-300 rounded" value="<?php echo e(request()->input('search')); ?>" placeholder="Search by name, reg. number, or program">
                    <button type="submit" class="ml-2 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                        Search
                    </button>
                </form>
            </div>

            

            <!-- Attendance Table -->
            <table class="table table-striped" id="myTable">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Reg_Number</th>
                        <th>Program</th>
                        <th>Gender</th>
                        <th>Status</th>
                        <th>Grade Percentage</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $__currentLoopData = $students; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $student): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                    <tr>
                        <td><?php echo e($student->name); ?></td>
                        <td><?php echo e($student->registration_number); ?></td>
                        <td><?php echo e($student->program_of_study); ?></td>
                        <td><?php echo e($student->gender); ?></td>
                        <td><?php echo e($student->status); ?></td>
                        <td>
                            <span class="<?php echo e($student->avg_grade < 50 ? 'bg-red-200 text-red-800 py-1 px-2 rounded-full' : 'bg-green-200 text-green-800 py-1 px-2 rounded-full'); ?>">
                                <?php echo e($student->avg_grade); ?>%
                            </span>
                        </td>
                        <td>
                            <span class="inline-flex">
                                <a href="<?php echo e(route('students.edit', $student)); ?>" class="text-blue-500 hover:text-blue-700 mr-2"><i class="fas fa-edit"></i></a>
                                <button onclick="openDeleteModal(<?php echo e($student->id); ?>)" class="text-red-500 hover:text-red-700 mr-2"><i class="fas fa-trash-alt"></i></button>
                                <a href="<?php echo e(route('students.qrcode', $student)); ?>" class="text-blue-500 hover:text-blue-700"><i class="fas fa-qrcode"></i></a>
                            </span>
                        </td>
                    </tr>
                    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                </tbody>
            </table>

            <!-- Pagination Links -->
            <div class="mt-4">
                <?php echo e($students->appends(['search' => request()->input('search')])->links()); ?>

            </div>
        </div>

        <!-- Modal HTML -->
        <div id="popup-modal" tabindex="-1" class="hidden overflow-y-auto  bg-gray-600 bg-opacity-50 hidden overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
            <div class="relative bg-white rounded-lg scale-in-bottom shadow dark:bg-gray-700">
                <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                    <button type="button" class="absolute top-3 end-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="popup-modal">
                        <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
                        </svg>
                        <span class="sr-only">Close modal</span>
                    </button>
                    <div class="p-4 md:p-5 text-center">
                        <svg class="mx-auto mb-4 text-gray-400 w-12 h-12 dark:text-gray-200" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 11V6m0 8h.01M19 10a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                        </svg>
                        <h3 class="mb-5 text-lg font-normal text-gray-500 dark:text-gray-400">Are you sure you want to delete this student?</h3>
                        <form id="delete-form" method="post">
                            <?php echo csrf_field(); ?>
                            <?php echo method_field('DELETE'); ?>
                            <button type="submit" class="text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center">
                                Yes, I'm sure
                            </button>
                            <button data-modal-hide="popup-modal" type="button" class="py-2.5 px-5 ms-3 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">No, cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>




    </div>

    <!-- Modal Background -->
    <div id="modal-bg" class="fixed inset-0 bg-gray-600 bg-opacity-50 hidden "></div>

    <!-- Modal -->
    <div id="modal" class="fixed inset-0 flex items-center mt-20 justify-center hidden scale-in-bottom">
        <div class="bg-white p-8 rounded shadow-lg w-1/3">
            <h2 class="text-xl mb-4">Import Students</h2>
            <form action="<?php echo e(route('students.import')); ?>" method="POST" enctype="multipart/form-data">
                <?php echo csrf_field(); ?>
                <div class="mb-4">
                    <label for="file" class="block text-sm font-medium text-gray-700">Choose Excel file</label>
                    <input type="file" name="file" id="file" required class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
                </div>
                <div class="flex justify-end">
                    <button type="button" onclick="closeModal()" class="mr-2 px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50">Cancel</button>
                    <button type="submit" class="px-4 py-2 text-sm font-medium text-white bg-blue-600 border border-transparent rounded-md hover:bg-blue-700">Import</button>
                </div>
            </form>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#myTable').DataTable({
                responsive: true,
                paging: false, // Disable pagination
                searching: false // Disable search functionality
            });
        });


        function openModal() {
            document.getElementById('modal').classList.remove('hidden');
            document.getElementById('modal-bg').classList.remove('hidden');
        }

        function closeModal() {
            document.getElementById('modal').classList.add('hidden');
            document.getElementById('modal-bg').classList.add('hidden');
        }

        setTimeout(function() {
            document.getElementById('successMessage').style.display = 'none';
        }, 3000); // 3000 milliseconds = 3 seconds
    </script>
    <script>
        function openDeleteModal(studentId) {
            // Set the action attribute of the form with the student ID
            document.getElementById('delete-form').action = `/students/${studentId}`;

            // Open the modal
            document.getElementById('popup-modal').classList.remove('hidden');
            document.getElementById('popup-modal').classList.add('flex');
        }

        // Close modal when cancel button is clicked
        document.querySelectorAll('[data-modal-hide="popup-modal"]').forEach((button) => {
            button.addEventListener('click', () => {
                document.getElementById('popup-modal').classList.add('hidden');
                document.getElementById('popup-modal').classList.remove('flex');
            });
        });
    </script>

    <script>
        function downloadTableAsExcel() {
            // Get the table element
            var table = document.getElementById('myTable');

            // Convert the table to a worksheet
            var workbook = XLSX.utils.table_to_book(table, {
                sheet: "Sheet1"
            });

            // Generate a binary string representation of the workbook
            var wbout = XLSX.write(workbook, {
                bookType: 'xlsx',
                type: 'binary'
            });

            // Create a Blob from the binary string
            var blob = new Blob([s2ab(wbout)], {
                type: 'application/octet-stream'
            });

            // Create a download link and trigger the download
            var link = document.createElement('a');
            link.href = URL.createObjectURL(blob);
            link.download = 'students_table.xlsx';
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
        }

        function s2ab(s) {
            var buf = new ArrayBuffer(s.length);
            var view = new Uint8Array(buf);
            for (var i = 0; i < s.length; i++) view[i] = s.charCodeAt(i) & 0xFF;
            return buf;
        }
    </script>

</body>

</html>

<?php $__env->stopSection(); ?>
<?php echo $__env->make('layouts.app', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\wamp64\www\New_Attendance_App\resources\views/student/attendance.blade.php ENDPATH**/ ?>